# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Profiles\alrego\Desktop\GUI_QA\mainWindows.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(491, 842)
        MainWindow.setStatusTip("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lToken = QtWidgets.QLabel(self.centralwidget)
        self.lToken.setGeometry(QtCore.QRect(10, 10, 471, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lToken.setFont(font)
        self.lToken.setAutoFillBackground(False)
        self.lToken.setStyleSheet("background-color: rgb(112, 112, 112);color:white;")
        self.lToken.setAlignment(QtCore.Qt.AlignCenter)
        self.lToken.setObjectName("lToken")
        self.gbRetrieveAvatar = QtWidgets.QGroupBox(self.centralwidget)
        self.gbRetrieveAvatar.setEnabled(True)
        self.gbRetrieveAvatar.setGeometry(QtCore.QRect(10, 170, 471, 131))
        self.gbRetrieveAvatar.setStyleSheet("QGroupBox:title {color: rgb(1, 130, 153);}")
        self.gbRetrieveAvatar.setObjectName("gbRetrieveAvatar")
        self.butRetrieveAvatar = QtWidgets.QPushButton(self.gbRetrieveAvatar)
        self.butRetrieveAvatar.setGeometry(QtCore.QRect(40, 20, 381, 23))
        self.butRetrieveAvatar.setStyleSheet("font-weight: normal;border: 2px solid #8f8f91; border-radius: 10px; background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #c0c0c0, stop: 1 #babbbe);")
        self.butRetrieveAvatar.setObjectName("butRetrieveAvatar")
        self.lUrl = QtWidgets.QLabel(self.gbRetrieveAvatar)
        self.lUrl.setGeometry(QtCore.QRect(10, 60, 451, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(False)
        font.setWeight(50)
        self.lUrl.setFont(font)
        self.lUrl.setStyleSheet("background-color:white;color:blue;")
        self.lUrl.setAlignment(QtCore.Qt.AlignCenter)
        self.lUrl.setObjectName("lUrl")
        self.butCopyLink = QtWidgets.QPushButton(self.gbRetrieveAvatar)
        self.butCopyLink.setGeometry(QtCore.QRect(190, 90, 100, 23))
        self.butCopyLink.setStyleSheet("font-weight: normal;border: 2px solid #8f8f91; border-radius: 10px; background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #c0c0c0, stop: 1 #babbbe);")
        self.butCopyLink.setObjectName("butCopyLink")
        self.JWTToken = QtWidgets.QLabel(self.gbRetrieveAvatar)
        self.JWTToken.setGeometry(QtCore.QRect(70, -20, 341, 30))
        self.JWTToken.setObjectName("JWTToken")
        self.gbRetrieveMetrics = QtWidgets.QGroupBox(self.centralwidget)
        self.gbRetrieveMetrics.setEnabled(True)
        self.gbRetrieveMetrics.setGeometry(QtCore.QRect(10, 320, 471, 441))
        self.gbRetrieveMetrics.setStyleSheet("QGroupBox:title {color: rgb(1, 130, 153);}")
        self.gbRetrieveMetrics.setObjectName("gbRetrieveMetrics")
        self.butMetricsRet = QtWidgets.QPushButton(self.gbRetrieveMetrics)
        self.butMetricsRet.setGeometry(QtCore.QRect(50, 240, 381, 23))
        self.butMetricsRet.setMinimumSize(QtCore.QSize(250, 20))
        self.butMetricsRet.setStyleSheet("font-weight: normal;border: 2px solid #8f8f91; border-radius: 10px; background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #c0c0c0, stop: 1 #babbbe);")
        self.butMetricsRet.setObjectName("butMetricsRet")
        self.butCopyMetrics = QtWidgets.QPushButton(self.gbRetrieveMetrics)
        self.butCopyMetrics.setGeometry(QtCore.QRect(190, 410, 100, 23))
        self.butCopyMetrics.setStyleSheet("font-weight: normal;border: 2px solid #8f8f91; border-radius: 10px; background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #c0c0c0, stop: 1 #babbbe);")
        self.butCopyMetrics.setObjectName("butCopyMetrics")
        self.cbMetricRet = QtWidgets.QComboBox(self.gbRetrieveMetrics)
        self.cbMetricRet.setEnabled(True)
        self.cbMetricRet.setGeometry(QtCore.QRect(150, 40, 191, 20))
        self.cbMetricRet.setObjectName("cbMetricRet")
        self.butAddMetricRet = QtWidgets.QPushButton(self.gbRetrieveMetrics)
        self.butAddMetricRet.setGeometry(QtCore.QRect(150, 70, 191, 20))
        self.butAddMetricRet.setMinimumSize(QtCore.QSize(0, 20))
        self.butAddMetricRet.setStyleSheet("font-weight: normal;border: 2px solid #8f8f91; border-radius: 10px; background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #c0c0c0, stop: 1 #babbbe);")
        self.butAddMetricRet.setObjectName("butAddMetricRet")
        self.listWidget_2 = QtWidgets.QListWidget(self.gbRetrieveMetrics)
        self.listWidget_2.setGeometry(QtCore.QRect(130, 110, 231, 101))
        self.listWidget_2.setObjectName("listWidget_2")
        self.lvMetricsRetrieved = QtWidgets.QListWidget(self.gbRetrieveMetrics)
        self.lvMetricsRetrieved.setGeometry(QtCore.QRect(70, 280, 341, 121))
        self.lvMetricsRetrieved.setObjectName("lvMetricsRetrieved")
        self.lModelID = QtWidgets.QLabel(self.centralwidget)
        self.lModelID.setGeometry(QtCore.QRect(170, 0, 389, 31))
        self.lModelID.setObjectName("lModelID")
        self.lStatus = QtWidgets.QLabel(self.centralwidget)
        self.lStatus.setGeometry(QtCore.QRect(80, 130, 361, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lStatus.setFont(font)
        self.lStatus.setStyleSheet("background-color:white;color:blue;")
        self.lStatus.setText("")
        self.lStatus.setAlignment(QtCore.Qt.AlignCenter)
        self.lStatus.setObjectName("lStatus")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(140, 80, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:rgb(0, 85, 127);")
        self.label_2.setObjectName("label_2")
        self.gbDataCode = QtWidgets.QGroupBox(self.centralwidget)
        self.gbDataCode.setEnabled(True)
        self.gbDataCode.setGeometry(QtCore.QRect(80, 40, 361, 81))
        self.gbDataCode.setStyleSheet("QGroupBox:title {color: rgb(1, 130, 153);}")
        self.gbDataCode.setObjectName("gbDataCode")
        self.JWTToken_2 = QtWidgets.QLabel(self.gbDataCode)
        self.JWTToken_2.setGeometry(QtCore.QRect(70, -20, 341, 30))
        self.JWTToken_2.setObjectName("JWTToken_2")
        self.leDataCode = QtWidgets.QLineEdit(self.gbDataCode)
        self.leDataCode.setGeometry(QtCore.QRect(150, 30, 141, 31))
        self.leDataCode.setText("")
        self.leDataCode.setAlignment(QtCore.Qt.AlignCenter)
        self.leDataCode.setObjectName("leDataCode")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(420, 770, 61, 30))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("D:\\Profiles\\alrego\\Desktop\\GUI_QA\\logo_IBV_small.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 770, 181, 31))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("D:\\Profiles\\alrego\\Desktop\\GUI_QA\\logo.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.gbDataCode.raise_()
        self.lToken.raise_()
        self.gbRetrieveAvatar.raise_()
        self.gbRetrieveMetrics.raise_()
        self.lModelID.raise_()
        self.lStatus.raise_()
        self.label_2.raise_()
        self.label.raise_()
        self.label_3.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 491, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Q01D3Deasy"))
        self.lToken.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">TOKEN     NOT     LOADED</span></p></body></html>"))
        self.gbRetrieveAvatar.setTitle(_translate("MainWindow", "Retrieve Model"))
        self.butRetrieveAvatar.setText(_translate("MainWindow", "Retrieve Avatar"))
        self.lUrl.setText(_translate("MainWindow", "-"))
        self.butCopyLink.setText(_translate("MainWindow", "Copy Link"))
        self.JWTToken.setText(_translate("MainWindow", "JWTTOKEN"))
        self.gbRetrieveMetrics.setTitle(_translate("MainWindow", "Retrieve Metrics"))
        self.butMetricsRet.setText(_translate("MainWindow", "Retrieve Metrics"))
        self.butCopyMetrics.setText(_translate("MainWindow", "Copy Metrics"))
        self.butAddMetricRet.setText(_translate("MainWindow", "Add Metric to Retrieving List"))
        self.lModelID.setText(_translate("MainWindow", "TransactionID:"))
        self.label_2.setText(_translate("MainWindow", "Data Code:"))
        self.gbDataCode.setTitle(_translate("MainWindow", "Data Code"))
        self.JWTToken_2.setText(_translate("MainWindow", "JWTTOKEN"))
import logo_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
