# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Profiles\alrego\Desktop\GUI_Q01D3D - clean\mainWindows.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(942, 804)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lToken = QtWidgets.QLabel(self.centralwidget)
        self.lToken.setGeometry(QtCore.QRect(20, 10, 901, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lToken.setFont(font)
        self.lToken.setAutoFillBackground(False)
        self.lToken.setStyleSheet("background-color: rgb(112, 112, 112);color:white;")
        self.lToken.setAlignment(QtCore.Qt.AlignCenter)
        self.lToken.setObjectName("lToken")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 40, 421, 561))
        self.groupBox.setAutoFillBackground(False)
        self.groupBox.setStyleSheet("QGroupBox:title {color: rgb(1, 130, 153);}")
        self.groupBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 10, 391, 859))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.LayInputs = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.LayInputs.setContentsMargins(0, 0, 0, 0)
        self.LayInputs.setObjectName("LayInputs")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setContentsMargins(2, 2, 2, 2)
        self.formLayout.setObjectName("formLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(0, QtWidgets.QFormLayout.LabelRole, spacerItem)
        self.lWeight = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lWeight.setObjectName("lWeight")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lWeight)
        self.sbWeight = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.sbWeight.setMinimum(0)
        self.sbWeight.setMaximum(2500)
        self.sbWeight.setProperty("value", 0)
        self.sbWeight.setObjectName("sbWeight")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.sbWeight)
        self.lHeight = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lHeight.setObjectName("lHeight")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lHeight)
        self.sbHeight = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.sbHeight.setMinimum(0)
        self.sbHeight.setMaximum(2500)
        self.sbHeight.setProperty("value", 0)
        self.sbHeight.setObjectName("sbHeight")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.sbHeight)
        self.lGender = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lGender.setObjectName("lGender")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lGender)
        self.cbGender = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.cbGender.setObjectName("cbGender")
        self.cbGender.addItem("")
        self.cbGender.addItem("")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.cbGender)
        self.lAge = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lAge.setObjectName("lAge")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.lAge)
        self.sbAge = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.sbAge.setObjectName("sbAge")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.sbAge)
        self.lCountryCode = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lCountryCode.setObjectName("lCountryCode")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.lCountryCode)
        self.cbCountryCode = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.cbCountryCode.setObjectName("cbCountryCode")
        self.cbCountryCode.addItem("")
        self.cbCountryCode.addItem("")
        self.cbCountryCode.addItem("")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.cbCountryCode)
        spacerItem1 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(7, QtWidgets.QFormLayout.LabelRole, spacerItem1)
        self.line = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.line)
        self.lMetrica = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lMetrica.setObjectName("lMetrica")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.lMetrica)
        self.cbMetrica = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.cbMetrica.setObjectName("cbMetrica")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.cbMetrica)
        self.lValue = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lValue.setObjectName("lValue")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.lValue)
        self.sbValue = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.sbValue.setMaximum(2500)
        self.sbValue.setObjectName("sbValue")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.sbValue)
        self.butAdd = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.butAdd.setMinimumSize(QtCore.QSize(0, 20))
        self.butAdd.setStyleSheet("font-weight: normal;border: 2px solid #8f8f91; border-radius: 10px; background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #c0c0c0, stop: 1 #babbbe);")
        self.butAdd.setObjectName("butAdd")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.butAdd)
        self.listWidget = QtWidgets.QListWidget(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget.sizePolicy().hasHeightForWidth())
        self.listWidget.setSizePolicy(sizePolicy)
        self.listWidget.setMinimumSize(QtCore.QSize(0, 200))
        self.listWidget.setObjectName("listWidget")
        self.formLayout.setWidget(14, QtWidgets.QFormLayout.FieldRole, self.listWidget)
        self.butClear = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.butClear.setMinimumSize(QtCore.QSize(0, 20))
        self.butClear.setBaseSize(QtCore.QSize(0, 20))
        self.butClear.setStyleSheet("font-weight: normal;border: 2px solid #8f8f91; border-radius: 10px; background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #c0c0c0, stop: 1 #babbbe);")
        self.butClear.setObjectName("butClear")
        self.formLayout.setWidget(15, QtWidgets.QFormLayout.FieldRole, self.butClear)
        spacerItem2 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(11, QtWidgets.QFormLayout.FieldRole, spacerItem2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(13, QtWidgets.QFormLayout.FieldRole, spacerItem3)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(14, QtWidgets.QFormLayout.LabelRole, self.label)
        self.LayInputs.addLayout(self.formLayout)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 620, 421, 101))
        self.groupBox_2.setStyleSheet("QGroupBox:title {color: rgb(1, 130, 153);}")
        self.groupBox_2.setObjectName("groupBox_2")
        self.butRunQ0 = QtWidgets.QPushButton(self.groupBox_2)
        self.butRunQ0.setGeometry(QtCore.QRect(20, 20, 389, 21))
        self.butRunQ0.setStyleSheet("font-weight: normal;border: 2px solid #8f8f91; border-radius: 10px; background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #c0c0c0, stop: 1 #babbbe);")
        self.butRunQ0.setObjectName("butRunQ0")
        self.lStatus = QtWidgets.QLabel(self.groupBox_2)
        self.lStatus.setGeometry(QtCore.QRect(40, 70, 46, 13))
        self.lStatus.setObjectName("lStatus")
        self.lStatusValue = QtWidgets.QLabel(self.groupBox_2)
        self.lStatusValue.setGeometry(QtCore.QRect(90, 60, 301, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lStatusValue.setFont(font)
        self.lStatusValue.setStyleSheet("background-color:white;color:blue")
        self.lStatusValue.setAlignment(QtCore.Qt.AlignCenter)
        self.lStatusValue.setObjectName("lStatusValue")
        self.gbRetrieveAvatar = QtWidgets.QGroupBox(self.centralwidget)
        self.gbRetrieveAvatar.setEnabled(True)
        self.gbRetrieveAvatar.setGeometry(QtCore.QRect(450, 40, 471, 171))
        self.gbRetrieveAvatar.setStyleSheet("QGroupBox:title {color: rgb(1, 130, 153);}")
        self.gbRetrieveAvatar.setObjectName("gbRetrieveAvatar")
        self.butRetrieveAvatar = QtWidgets.QPushButton(self.gbRetrieveAvatar)
        self.butRetrieveAvatar.setGeometry(QtCore.QRect(50, 40, 381, 23))
        self.butRetrieveAvatar.setStyleSheet("font-weight: normal;border: 2px solid #8f8f91; border-radius: 10px; background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #c0c0c0, stop: 1 #babbbe);")
        self.butRetrieveAvatar.setObjectName("butRetrieveAvatar")
        self.lUrl = QtWidgets.QLabel(self.gbRetrieveAvatar)
        self.lUrl.setGeometry(QtCore.QRect(10, 99, 451, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lUrl.setFont(font)
        self.lUrl.setStyleSheet("background-color:white;color:blue;")
        self.lUrl.setAlignment(QtCore.Qt.AlignCenter)
        self.lUrl.setObjectName("lUrl")
        self.butCopyLink = QtWidgets.QPushButton(self.gbRetrieveAvatar)
        self.butCopyLink.setGeometry(QtCore.QRect(200, 130, 100, 23))
        self.butCopyLink.setStyleSheet("font-weight: normal;border: 2px solid #8f8f91; border-radius: 10px; background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #c0c0c0, stop: 1 #babbbe);")
        self.butCopyLink.setObjectName("butCopyLink")
        self.gbRetrieveMetrics = QtWidgets.QGroupBox(self.centralwidget)
        self.gbRetrieveMetrics.setEnabled(True)
        self.gbRetrieveMetrics.setGeometry(QtCore.QRect(450, 220, 471, 501))
        self.gbRetrieveMetrics.setStyleSheet("QGroupBox:title {color: rgb(1, 130, 153);}")
        self.gbRetrieveMetrics.setObjectName("gbRetrieveMetrics")
        self.butMetricsRet = QtWidgets.QPushButton(self.gbRetrieveMetrics)
        self.butMetricsRet.setGeometry(QtCore.QRect(10, 260, 441, 23))
        self.butMetricsRet.setMinimumSize(QtCore.QSize(250, 20))
        self.butMetricsRet.setStyleSheet("font-weight: normal;border: 2px solid #8f8f91; border-radius: 10px; background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #c0c0c0, stop: 1 #babbbe);")
        self.butMetricsRet.setObjectName("butMetricsRet")
        self.butCopyMetrics = QtWidgets.QPushButton(self.gbRetrieveMetrics)
        self.butCopyMetrics.setGeometry(QtCore.QRect(190, 460, 100, 23))
        self.butCopyMetrics.setStyleSheet("font-weight: normal;border: 2px solid #8f8f91; border-radius: 10px; background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #c0c0c0, stop: 1 #babbbe);")
        self.butCopyMetrics.setObjectName("butCopyMetrics")
        self.cbMetricRet = QtWidgets.QComboBox(self.gbRetrieveMetrics)
        self.cbMetricRet.setEnabled(True)
        self.cbMetricRet.setGeometry(QtCore.QRect(10, 42, 443, 20))
        self.cbMetricRet.setObjectName("cbMetricRet")
        self.butAddMetricRet = QtWidgets.QPushButton(self.gbRetrieveMetrics)
        self.butAddMetricRet.setGeometry(QtCore.QRect(10, 74, 443, 20))
        self.butAddMetricRet.setMinimumSize(QtCore.QSize(0, 20))
        self.butAddMetricRet.setStyleSheet("font-weight: normal;border: 2px solid #8f8f91; border-radius: 10px; background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #c0c0c0, stop: 1 #babbbe);")
        self.butAddMetricRet.setObjectName("butAddMetricRet")
        self.listWidget_2 = QtWidgets.QListWidget(self.gbRetrieveMetrics)
        self.listWidget_2.setGeometry(QtCore.QRect(70, 120, 341, 121))
        self.listWidget_2.setObjectName("listWidget_2")
        self.lvMetricsRetrieved = QtWidgets.QListWidget(self.gbRetrieveMetrics)
        self.lvMetricsRetrieved.setGeometry(QtCore.QRect(70, 310, 341, 121))
        self.lvMetricsRetrieved.setObjectName("lvMetricsRetrieved")
        self.lstatusRetMet = QtWidgets.QLabel(self.gbRetrieveMetrics)
        self.lstatusRetMet.setGeometry(QtCore.QRect(50, 450, 381, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lstatusRetMet.setFont(font)
        self.lstatusRetMet.setStyleSheet("background-color:white;color:blue;")
        self.lstatusRetMet.setText("")
        self.lstatusRetMet.setAlignment(QtCore.Qt.AlignCenter)
        self.lstatusRetMet.setObjectName("lstatusRetMet")
        self.JWTToken = QtWidgets.QLabel(self.centralwidget)
        self.JWTToken.setGeometry(QtCore.QRect(280, -10, 341, 30))
        self.JWTToken.setObjectName("JWTToken")
        self.lModelID = QtWidgets.QLabel(self.centralwidget)
        self.lModelID.setGeometry(QtCore.QRect(610, 0, 389, 31))
        self.lModelID.setObjectName("lModelID")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 90, 120, 80))
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(860, 730, 61, 31))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("D:\\Profiles\\alrego\\Desktop\\GUI_Q01D3D - clean\\logo_IBV_small.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(670, 730, 181, 31))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("D:\\Profiles\\alrego\\Desktop\\GUI_Q01D3D - clean\\logo.png"))
        self.label_3.setScaledContents(False)
        self.label_3.setObjectName("label_3")
        self.groupBox_2.raise_()
        self.groupBox.raise_()
        self.lToken.raise_()
        self.gbRetrieveAvatar.raise_()
        self.gbRetrieveMetrics.raise_()
        self.JWTToken.raise_()
        self.lModelID.raise_()
        self.frame.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 942, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Q01D3Deasy"))
        self.lToken.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">TOKEN     NOT     LOADED</span></p></body></html>"))
        self.groupBox.setTitle(_translate("MainWindow", "Input Data"))
        self.lWeight.setText(_translate("MainWindow", "Weight(kg):"))
        self.lHeight.setText(_translate("MainWindow", "Height(mm):"))
        self.lGender.setText(_translate("MainWindow", "Gender:"))
        self.cbGender.setItemText(0, _translate("MainWindow", "male"))
        self.cbGender.setItemText(1, _translate("MainWindow", "female"))
        self.lAge.setText(_translate("MainWindow", "Age:"))
        self.lCountryCode.setText(_translate("MainWindow", "CountryCode:"))
        self.cbCountryCode.setItemText(0, _translate("MainWindow", "IT"))
        self.cbCountryCode.setItemText(1, _translate("MainWindow", "ES"))
        self.cbCountryCode.setItemText(2, _translate("MainWindow", "PT"))
        self.lMetrica.setText(_translate("MainWindow", "Metric:"))
        self.lValue.setText(_translate("MainWindow", "Value:"))
        self.butAdd.setText(_translate("MainWindow", "Add Metric to Query"))
        self.butClear.setText(_translate("MainWindow", "Clear Metrics"))
        self.label.setText(_translate("MainWindow", "Metrics in query:"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Query execution"))
        self.butRunQ0.setText(_translate("MainWindow", "Run Query"))
        self.lStatus.setText(_translate("MainWindow", "Status:"))
        self.lStatusValue.setText(_translate("MainWindow", "TextLabel"))
        self.gbRetrieveAvatar.setTitle(_translate("MainWindow", "Retrieve Model"))
        self.butRetrieveAvatar.setText(_translate("MainWindow", "Retrieve Avatar"))
        self.lUrl.setText(_translate("MainWindow", "-"))
        self.butCopyLink.setText(_translate("MainWindow", "Copy Link"))
        self.gbRetrieveMetrics.setTitle(_translate("MainWindow", "Retrieve Metrics"))
        self.butMetricsRet.setText(_translate("MainWindow", "Retrieve Metrics"))
        self.butCopyMetrics.setText(_translate("MainWindow", "Copy Metrics"))
        self.butAddMetricRet.setText(_translate("MainWindow", "Add Metric to Retrieving List"))
        self.JWTToken.setText(_translate("MainWindow", "JWTTOKEN"))
        self.lModelID.setText(_translate("MainWindow", "TransactionID:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
